name: Flutter CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Create Firebase config file for Android
      run: echo "${{ secrets.ANDROID_FIREBASE_CONFIG }}" > android/app/google-services.json
      shell: bash

    - name: Create Firebase config file for iOS
      run: echo "${{ secrets.IOS_FIREBASE_CONFIG }}" > ios/Runner/GoogleService-Info.plist
      shell: bash
    
    - name: Create Firebase options file
      run: echo "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart
      shell: bash

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test